### ISSUE TITLE
Support for arcsine function

### ISSUE THREAD

**Issue by patel-zeel** [wesselb/lab#1]
I was trying to implement the [mlp kernel](https://gpy.readthedocs.io/en/deploy/GPy.kern.src.html#module-GPy.kern.src.mlp) but could not find ```B.arcsin()``` function. Is there a workaround for this?

**Comment by wesselb** [comment]
Hey @patel-zeel! You're right that that `B.arc*` are currently not available. I'll add those later today, which should be an easy job!

**Comment by patel-zeel** [comment]
Thanks a lot, @wesselb :)

**Comment by wesselb** [comment]
Np at all! :) These functions are now available in `v1.3.0`.
