### ISSUE TITLE
help

### ISSUE THREAD

**Issue by userguazi** [wesselb/lab#13]
In file included from lab/bvn_cdf/bvn_cdf.c:1577:0:
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:40:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic _Bool atomic_bool;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:41:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic char atomic_char;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:42:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic signed char atomic_schar;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:43:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic unsigned char atomic_uchar;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:44:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic short atomic_short;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:45:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic unsigned short atomic_ushort;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:46:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic int atomic_int;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:47:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic unsigned int atomic_uint;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:48:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic long atomic_long;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:49:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic unsigned long atomic_ulong;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:50:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic long long atomic_llong;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:51:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic unsigned long long atomic_ullong;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:52:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __CHAR16_TYPE__ atomic_char16_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:53:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __CHAR32_TYPE__ atomic_char32_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:54:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __WCHAR_TYPE__ atomic_wchar_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:55:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INT_LEAST8_TYPE__ atomic_int_least8_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:56:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINT_LEAST8_TYPE__ atomic_uint_least8_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:57:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INT_LEAST16_TYPE__ atomic_int_least16_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:58:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINT_LEAST16_TYPE__ atomic_uint_least16_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:59:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INT_LEAST32_TYPE__ atomic_int_least32_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:60:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINT_LEAST32_TYPE__ atomic_uint_least32_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:61:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INT_LEAST64_TYPE__ atomic_int_least64_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:62:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINT_LEAST64_TYPE__ atomic_uint_least64_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:63:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INT_FAST8_TYPE__ atomic_int_fast8_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:64:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINT_FAST8_TYPE__ atomic_uint_fast8_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:65:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INT_FAST16_TYPE__ atomic_int_fast16_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:66:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINT_FAST16_TYPE__ atomic_uint_fast16_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:67:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INT_FAST32_TYPE__ atomic_int_fast32_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:68:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINT_FAST32_TYPE__ atomic_uint_fast32_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:69:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INT_FAST64_TYPE__ atomic_int_fast64_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:70:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINT_FAST64_TYPE__ atomic_uint_fast64_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:71:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INTPTR_TYPE__ atomic_intptr_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:72:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINTPTR_TYPE__ atomic_uintptr_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:73:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __SIZE_TYPE__ atomic_size_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:74:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __PTRDIFF_TYPE__ atomic_ptrdiff_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:75:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __INTMAX_TYPE__ atomic_intmax_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:76:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic __UINTMAX_TYPE__ atomic_uintmax_t;
 ^~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/6/include/stdatomic.h:218:1: sorry, unimplemented: ‘_Atomic’ with OpenMP
 typedef _Atomic struct
 ^~~~~~~
error: command '/usr/bin/gcc' failed with exit code 1
what should i do？

**Comment by wesselb** [comment]
Hey @userguazi! If you don't need `B.bvn_cdf`, then you can disable compilation by

```bash
export LAB_NO_COMPILE=1
```

before installing. That should circumvent the compilation step.

**Comment by userguazi** [comment]
> Hey @userguazi! If you don't need `B.bvn_cdf`, then you can disable compilation by
> 
> ```shell
> export LAB_NO_BUILD=1
> ```
> 
> before installing. That should circumvent the compilation step.

thank you！

**Comment by wesselb** [comment]
@userguazi Glad to help! Will close this issue now, but please reopen if the problem persists. :)
