### ISSUE TITLE
conda installation

### ISSUE THREAD

**Issue by ctr** [wesselb/lab#17]
Hi

Is it possible to install wesselb/lab directly using conda? Do you provide packages for any conda repo?

Thanks

Chris.

**Comment by wesselb** [comment]
Hey Chris,

We currently do not provide a package on Conda, but this would certainly be possible to do.

Is this something you'd like, so you could `conda install backends`?

**Comment by ctr** [comment]
Yes that would be useful if you have time. Many thanks. Chris.

**Comment by wesselb** [comment]
@ctr Alright, will do! Will report back here when that's done. :)

**Comment by wesselb** [comment]
Hey @ctr! You should now be able to install `lab` with `conda install backends -c conda-forge`. :)
