### ISSUE TITLE
create_random_state fails for pytorch 2.0.0

### ISSUE THREAD

**Issue by manuelhaussmann** [wesselb/lab#9]
With pytorch 2.0.0 and the latest version of lab, `create_random_state` fails for `torch.float32` and `torch.float64`.

```
import lab as B
import torch as th
B.create_random_state(th.float32, seed=0)
```
gives
```NotFoundLookupError: For function `create_random_state`, `(torch.float64,)` could not be resolved.```

Numpy data types work without a problem.

**Comment by wesselb** [comment]
Hey @manuelhaussmann! Thanks for raising this, and I'm sorry for the slow reply. Been away on holiday and to a conference, and I'm only now catching up on email.

This is a pretty severe bug. I'll put PyTorch 2.0 compatibility high on my list of TODOs.

**Comment by wesselb** [comment]
Hey @manuelhaussmann! I've just looked into this. I believe you might have forgotten to activate the PyTorch extension by importing `lab.torch`. I get the following with the latest versions of `torch` and LAB:

```python
>>> import lab.torch as B   # Note `lab.torch` here, not just `lab`.

>>> import torch

>>> B.create_random_state(torch.float32)
<torch._C.Generator object at 0x7f8f408557b0>
```

Could you check whether that also works for you?

**Comment by manuelhaussmann** [comment]
Yes, it works perfectly. I had indeed just missed `lab.torch`. Thanks and sorry for the confusion!

**Comment by wesselb** [comment]
No problem at all! Thanks for the speedy reply. :)
